### ISSUE TITLE
Update to work with latest r3f (^6) and drei (^4)

### ISSUE THREAD

**Issue by robhawkes** [pmndrs/react-three-lightmap#11]
### Expectation
- `react-three-lightmap` works with most recent r3f (6.0.13) and drei (5.1.17)

### Actual
- `react-three-lightmap` doesn't work if r3f is above version 5 and if drei is above version 3

### Notes
- r3f dependency for `react-three-lightmap` is currently set to `react-three-fiber` (legacy?)
- Drei dependency for `react-three-lightmap` is set to a much older v3 (current is v5)

### Example
- [This CodeSandbox works as expected](https://codesandbox.io/s/react-three-lightmap-working-23qi5)
- Changing the r3f dependency on the above sandbox to 6 or above causes things to stop working
- Changing the drei dependency on the above sandbox to 4 or above causes things to stop working

![image](https://user-images.githubusercontent.com/22612/119275551-b14ad400-bc0d-11eb-867d-b2b1a7ba44a6.png)

**Comment by unframework** [comment]
Thanks for catching this! I finally got around to doing some maintenance recently (busy year!). Upgraded dependencies to r3f v6+ and drei v7+ and I *think* I took care of most of the issues, please see v0.0.3.

One caveat is that you need to specify `mode="legacy"` on the Canvas element, otherwise it won't work. Please let me know if more issues come up.
